### ISSUE TITLE
Add Jonathan as member to test process

### ISSUE THREAD

**Issue by LucyMcGowan** [wfu-dmds/dmds-website#1]
@jdtrat Can you please add yourself as a member? Right now I have it set up so you would:

* Create a file `jonathan.md` under `content > member` (you can copy my `lucy.md` as a template)
* Fill it out
* Add `jonathan.png` (or whatever you save your portrait as) to the `static > img` folder

**Comment by jdtrat** [comment]
I restructured the members section of the website. I'm not sure if continuous deployment is enabled on Netlify (I don't think it is because the live site is not updating), but there will be a [people](https://dmds.lucymcgowan.com/people/) page that displays all the authors under the content > authors directory. I'll create a new issue describing how to add other members shortly.
